HIFB_SRC +=drv/$(ARCH_DIR)/hifb_vou_drv.c \
	drv/$(ARCH_DIR)/hifb_blit.c \
	drv/$(ARCH_DIR)/hifb_vou_graphics.c \
	drv/$(ARCH_DIR)/hifb_graphics_drv.c \
	drv/$(ARCH_DIR)/hifb_graphic_hal.c \
	drv/$(ARCH_DIR)/gf_ghdr_lut.c
